- .github/actions/yarn-install/action.yml
- .github/workflows/test-build.yaml
- jest.config.cjs
> Jest Testing Pt. II

- packages/frontend/src/components/button.tsx
- packages/frontend/src/components/icon.tsx
> Finalising Buttons

- packages/frontend/src/components/stars.tsx
Made changes that Sammy requested (something about disabled)
> Fixed issue #45

- jest.config.cjs
- package.json
- packages/frontend/tests/__setup__.ts
- packages/frontend/tests/stars.test.tsx
- yarn.lock
Whooops! Should have been done from the start.
Quick! Merge it before anyone notices!
> Frontend Testing: Add startup script to allow Jest DOM methods.

- packages/db-client/src/collection.ts
- packages/db-client/tests/collection.test.ts
Takes the edit with query function from #68 and adds tests for it
Unit test has been added for the function
> Add edit with query

- packages/backend/src/league/league_controller.ts
- packages/backend/src/lib/utils.ts
- packages/backend/src/match/match_controller.ts
- packages/backend/tests/controllers/league.test.ts
- packages/backend/tests/controllers/match.test.ts
- packages/backend/tests/controllers/user.test.ts
- packages/backend/tests/helpers/controller.ts
- packages/backend/tests/lib/utils.test.ts
There were a few endpoints with TODOs left in #35 mentioned in #63 
- Moves equality check for inviteCode to use security safe one
- Adds checks to validate ids given in match creation actually exist
> Finish backend endpoints marked as TODO

- packages/api-client/src/sub/match.ts
- packages/api-client/tests/sub/match.test.ts
- packages/backend/src/league/league_controller.ts
- packages/backend/src/lib/types.ts
- packages/backend/src/match/match_controller.ts
- packages/backend/src/user/user_controller.ts
- packages/backend/tests/controllers/match.test.ts
- packages/types/src/match.ts
- packages/types/src/utils.ts
- packages/types/tests/utils.ts
https://trello.com/c/tzYrVzwt/86-add-endpoint-for-finishing-a-match
https://trello.com/c/6vlAauwe/88-add-endpoint-for-getting-proposed-matches
Adds endpoints which are useful for editing matches and are required for pages.
- Endpoint for getting proposed matches
- Endpoint for accepting proposed matches
- Endpoint for submitting a completed match
Tests have been added for all new functions (however I haven't run them yet)
> Add useful endpoints for matches

- packages/frontend/src/components/input.tsx
- packages/frontend/src/components/radio_button.tsx
Created 4 inputs: text box, text area, time, and date. Time and date haven't been customised to the figma because of limitations on the html date and time pickers, but they are functional. You can change the background color and placeholder text with props.
> Thomas canning input

- jest.config.cjs
- packages/frontend/tsconfig.json
Fixes the weird bug with transforms that happens when ts-jest sometimes.
> Fix `ts-jest` transform bug.

- packages/frontend/src/components/profile_pic.tsx
- packages/frontend/src/components/tags.tsx
- packages/frontend/tailwind.config.js
- packages/types/src/user.ts
- packages/types/tests/user.test.ts
- packages/types/tests/utils.ts
I have created the profile pic component, you can select a sport and it will show your ability level for that sport
> Add profile picture component

- packages/frontend/src/lib/async.tsx
- packages/frontend/tests/lib/async.test.tsx
* `useAsync` now supports refreshing (re-running the async function), using the optional `{ refresh: true }` option: `useAsync(async () => doStuff(), { refresh: true })`. You're then provided with an extra `refresh` function along with the usual gang: `loading`, `error`, `ok`.
* `useAsync` now attempts to "throw" the error upwards by default (using the `ErrorHandler` React context), or `console.error` if there is no available error handler.
> `useAsync`: Add refreshing and better error handling defaults.

- packages/api-client/src/sub/match.ts
- packages/backend/src/league/league_controller.ts
- packages/backend/src/match/match_controller.ts
- packages/backend/src/user/user_controller.ts
- packages/backend/tests/controllers/match.test.ts
- packages/backend/tests/controllers/user.test.ts
- packages/types/src/db_client.ts
- packages/types/src/league.ts
- packages/types/src/match.ts
- packages/types/src/user.ts
Cherry-picked the changes as sammy accidentally removed them from his branch
Backend unit tests should cover all the basis
> Fix SortQuery to work properly with TSOA

- packages/frontend/src/components/bottom_bar.tsx
- packages/frontend/src/components/button.tsx
- packages/frontend/src/components/card/matchcard.tsx
- packages/frontend/src/components/card_list.tsx
- packages/frontend/src/components/error.tsx
- packages/frontend/src/components/form/index.tsx
- packages/frontend/src/components/form/input.tsx
- packages/frontend/src/components/form/profile_picture.tsx
- packages/frontend/src/components/form/radio_button.tsx
- packages/frontend/src/components/form/select_sports.tsx
- packages/frontend/src/components/page/index.tsx
- packages/frontend/src/components/profile_pic.tsx
- packages/frontend/src/components/search.tsx
- packages/frontend/src/components/stars.tsx
- packages/frontend/src/components/tags.tsx
- packages/frontend/src/pages/test.tsx
- packages/frontend/tests/components/bottom_bar.test.tsx
- packages/frontend/tests/components/card/matchcard.test.tsx
- packages/frontend/tests/components/form/select_sports.test.tsx
- packages/frontend/tests/page.test.tsx
- packages/frontend/tests/stars.test.tsx
- packages/types/src/user.ts
This is a collection of improvements to components (mostly for improving usability but some syntactical stuff) that I have made while creating pages
> General component improvements

- packages/frontend/src/components/form/index.tsx
- packages/frontend/src/components/page/index.tsx
Uses slotting for the form object and uses `Page` behind the scenes for easy integration
Was there any in the first place?
> Move form to be a page obj

- packages/api-client/src/sub/user.ts
- packages/backend/src/lib/utils.ts
- packages/backend/src/user/user_controller.ts
- packages/types/src/api.ts
https://trello.com/c/zHqBkC9g/76-backend-recommending-algorithm
Adds endpoint for getting recommendations for other users
Uhhhhhhhhhhh I gotta go
> Add endpoint for getting recommended users

- packages/backend/src/user/user_controller.ts
- packages/backend/tests/controllers/user.test.ts
- packages/frontend/package.json
- packages/frontend/src/app.tsx
- packages/frontend/src/components/page/index.tsx
- packages/frontend/src/pages/match/new.tsx
- yarn.lock
https://trello.com/c/LtXlLFRy/47-frontend-form-page-new-match
Blocked on #76 
- Adds page for creating a new match
- Uses the async select from `react-select` for the opponent
- Fixes bug with the user `find` endpoint with it not correctly filtering sports
Successfully submitted match
> Add page for creating new matches

- packages/frontend/src/app.tsx
- packages/frontend/src/components/page/index.tsx
- packages/frontend/src/pages/profile.tsx
- packages/types/src/user.ts
- packages/types/tests/user.test.ts
https://trello.com/c/IA0to56h/66-frontend-int-page-other-profile-view
Adds a page which allows you to view other users information
Tested with a page which you have to scroll
> Add page for viewing other users information

- packages/frontend/src/app.tsx
- packages/frontend/src/components/icon.tsx
- packages/frontend/src/pages/new_league.tsx
https://trello.com/c/7KFWdEgc/46-frontend-form-page-new-league
Blocked on #76 
I have made it so it looks right but am not sure right now how to connect it to the api or how to form works (there is a submit button that comes from form when I believe the create button should be used to do the job instead)
* Submitted league
> Add page for creating new league

- packages/backend/src/app.ts
> Fix use of user controlled values being put through formatting

- packages/frontend/src/pages/league/new.tsx
- packages/frontend/src/pages/signup.tsx
Just random fixes found when doing videos
> Fix padding on form pages

- packages/backend/src/lib/availability_cache.ts
- packages/backend/src/match/match_controller.ts
Forgotten feature, we should remove people from being available on a given hour when a match is accepted.
This uses the cache which assumes the match is within the next two weeks
> Remove peoples availability when accepting a match

- jest.config.cjs
- packages/frontend/.eslintrc.cjs
- packages/frontend/src/components/card/feed.tsx
- packages/frontend/src/lib/async.tsx
- packages/frontend/src/pages/match/complete.tsx
- packages/frontend/src/pages/me/edit.tsx
- packages/frontend/src/pages/profile.tsx
- packages/frontend/src/pages/signup.tsx
- packages/frontend/tests/app.test.tsx
- packages/frontend/tests/components/card/feed.test.tsx
- packages/frontend/tests/lib/auth.test.tsx
- packages/frontend/tests/pages/helpers/index.tsx
- packages/frontend/tests/pages/league/discover.test.tsx
- packages/frontend/tests/pages/league/new.test.tsx
- packages/frontend/tests/pages/league/single.test.tsx
- packages/frontend/tests/pages/league/your.test.tsx
- packages/frontend/tests/pages/match/complete.test.tsx
- packages/frontend/tests/pages/match/index.test.tsx
- packages/frontend/tests/pages/match/new.test.tsx
- packages/frontend/tests/pages/match/proposal.test.tsx
- packages/frontend/tests/pages/match/upcoming.test.tsx
- packages/frontend/tests/pages/me/availability.test.tsx
- packages/frontend/tests/pages/me/edit.test.tsx
- packages/frontend/tests/pages/me/index.test.tsx
- packages/frontend/tests/pages/profile.test.tsx
- packages/frontend/tests/pages/signup.test.tsx
- packages/frontend/tests/pages/suggested_people.test.tsx
Will fix #110 in conjunction with @WilfSilver's work on components + utils.
> Add unit tests for Pages.
